# Generated by Django 5.1.1 on 2024-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
    ]
